### ISSUE TITLE
[BUG] Fuel Rod Gun and possibly all other "fixed-weapon" integrated mounts do not preserve custom names, descriptions, or notes across a page reload (as of ver. 2.3)

### ISSUE THREAD

**Issue by aWinglessMonkey** [massif-press/compcon#1915]
The special integrated-weapon "Fuel Rod Gun" never preserves custom names, descriptions, or notes (or its "uses" counter, which appears to be unique to it in the mech's loadout-sheet), even in situations when other weapons and systems do.

1. Create a new pilot, set them to license level 2 or higher, select all three levels of the Nuclear Cavalier talent, then create any mech for that character, which will have the Fuel Rod Gun installed.
2. Attempt to change the name or description for the Fuel Rod Gun, or add a note.  Install one other weapon in a normal mount and do the same.
3. Navigate away from the mech sheet and back to see the changed names and descriptions (though as of 2.3, sometimes weapons and systems (and pilot gear) often seem to update the display of these immediately, but not always, while the Fuel Rod Gun won't ever as far as I can tell).
4. Refresh the page, wait a few seconds to make sure any changes that survived the reload also survive the smart-sync (a probably-unrelated problem that has complicated my testing), and compare.  The Fuel Rod Gun will have reverted to "Fuel Rod Gun" and its default description and no notes, and its "uses" counter will be at 3 regardless of the maximum (which increases with engineering skill points)

What *should* happen is that any time the names, descriptions, and notes of the Fuel Rod Gun are changed, they should be saved and preserved in the same manner as for other weapons and systems.  Note that, prior to 2.3, they *were* preserved during refreshes, at least locally, and at least until I changed any pilot-talent upon which the weapon would be reset to the same state as described above.

Screenshot before refresh:
![image](https://user-images.githubusercontent.com/13388802/163288628-9f271a19-6534-4290-a803-32646308158f.png)

Screenshot after refresh:
![image](https://user-images.githubusercontent.com/13388802/163288939-224050f0-05a2-4587-a306-ec75b5b247a0.png)

While the Integrated Weapon core-bonus was included for demonstration purposes, I've tested without it and this issue occurs regardless of its presence.

Also, this issue appears to affect the Caliban's HHS-075 “Flayer” Shotgun, the Barbarossa's Apocalypse Rail, and the Sherman's ZF4 Solidcore in the same manner as it affects the Fuel Rod Gun.  It likely affects any integrated mount with "fixed" equipment in the same manner, but I have yet to identify what all of those are (the Pegasus does not appear to have one, for example, and that was the first I looked for).   Note that the Apocalypse Rail *also* has what appears to be an active-mode UI-feature visible on the loadout-sheet, but the out-of-place UI-features may be entirely unconnected to this.

(Edit: confirmed that it applies to the Prototype Weapon from the Engineer talent as well.)

Another issue (alluded to above), involving the smart-sync undoing recent changes even when the local application remembered them, has complicated the testing of this issue, as refreshing the page to provoke this one can also provoke the other (as can manually smart-syncing without a refresh).  These issues appear to be completely unrelated, as when refreshing the mech's loadout-sheet directly, if the smart-sync issue occurs, normal weapons & systems will have their changes visible for a few seconds before the smart-sync erases them (possibly with the entire equipment-piece itself when it gets really bad), while the Fuel Rod Gun and other affected weapons will be in their unchanged states immediately.

 - OS: Windows 10
 - Browser: Vivaldi (5.2.2623.33)
 - Comp/Con 2.3.2a

**Comment by TranslucentSabre** [comment]
Just as another data point. I also see this behavior with one of my player's Prototype weapon from the "Engineer" talent.

**Comment by jarena3** [comment]
This should be fixed as of 2.3.5. There's an additional issue with integrated equipment (#1952) that'll be resolved in the (hopefully) next update

**Comment by msprijatelj** [comment]
I just tested this with a Raleigh’s Mjolnir, and it looks like it’s still an issue. However, the Custom Name field is still *present*, it just gets rewritten to the default name. For example, on a refresh, the name header becomes “M7 Mjolnir // M7 Mjolnir”. 

Before:
![E05AE105-C32F-4486-8A21-D7641BFE963B](https://user-images.githubusercontent.com/44978587/164297109-b277e59c-9148-4453-ab61-6144f90c7ffd.png)
![B18DBDD8-0959-47FE-93C1-ACE7091D3FD7](https://user-images.githubusercontent.com/44978587/164297111-bfbd2432-5d61-4abe-8d94-264ada992320.png)

After:
![A454543F-3BD7-4018-A749-FBC5BE70A63E](https://user-images.githubusercontent.com/44978587/164297182-e92653d1-0fc9-4db7-a14e-57cfc3bfa095.png)
![D13B8417-D81A-4AE7-8E88-FF9115E67EDB](https://user-images.githubusercontent.com/44978587/164297184-d3063402-3c7c-471c-ad43-787594c50e28.png)

**Comment by TranslucentSabre** [comment]
In contrast I was just testing this with one of my players "Prototype III" weapon. It kept all of it's custom data "Name", "Uses", and "Damage Type" when I navigated to the compendium or to another mech. But, it lost all of it's data on a refresh of the tab.

This is an improvement, it used to lose everything whenever I simply navigated away.

**Comment by msprijatelj** [comment]
On COMP/CON V2.3.6, I repeated the steps my steps from above. The only difference was that this time, the custom flavor name was already initialized with the Compendium name. If i changed the Custom name, refreshing still reset the custom weapon name to match the Compendium name. Same browser as previous, still logged out of CompCon.

**Comment by msprijatelj** [comment]
OKAY! More context: Tested this again on Firefox Desktop and it worked fine.  So it may have something to do with the mobile browser I was using.  I'm going to close this for now, though, as it seems like this has been sorted out.

**Comment by TranslucentSabre** [comment]
In my mobile, installed Chrome version of Comp/Con version 2.3.6a, this is still an issue. Prototype weapon losses all customization on page reload. I will also test a desktop version when I have the chance.

**Comment by TranslucentSabre** [comment]
None of the prototype weapon custom info is saved upon page reload on either Chrome or Firefox  desktop browsers.

**Comment by msprijatelj** [comment]
@jarena3 My tests on 2.3.6 on iOS Mobile Firefox indicated that the issue occurred on talent-granted and frame-granted integrated weapons, but NOT the integrated weapon granted by Improved Armament.

**Comment by TranslucentSabre** [comment]
I have only been testing with Prototype Weapon, specifically because one of my players is using it.

**Comment by aWinglessMonkey** [comment]
As of 2.3.6a on Vivaldi on Windows 10, it's no longer forgetting custom names or use-counts for the Fuel Rod Gun, Prototype Weapon, or the Apocalypse Rail, at least for me (not counting the occasional cloud-sync issue).

Tangent: this should probably go in a different ticket at this point, but weapon-mods let you rename them yet don't remember it at all either, in a very similar way; they were just as uncooperative before 2.3, though, and so much less of a bother to me that I had forgotten about it.
